remote_theme: pages-themes/architect@v0.2.0
plugins:
    - jekyll-remote-theme

title: Sunday Mass Labelmaker
description: A small webapp for generating CSVs to turn into date and time labels. Made for the Liturgy team in Campus Ministry at Loyola Marymount University.
show_downloads: false
